package graph

import (
	"context"
	"encoding/json"
	"testing"

	"github.com/zimwip/goap/pkg/domain"
	"github.com/zimwip/goap/pkg/journal"
	"github.com/zimwip/goap/pkg/prov"
)

func TestProvenanceExport(t *testing.T) { forEachRepo(t, testProvenanceExport) }

// The log of an applied change exports as PROV-O (ADR 0057): the change and its runs are activities, the facts and
// node versions entities generated by the run that produced them, revising the version they started from, judged by
// a review, members of the baseline they landed in.
func testProvenanceExport(t *testing.T, repo Repo) {
	ctx := context.Background()
	f := newFixture(t, repo)
	g := f.g
	c, err := g.CreateChange(ctx, NewChange{Title: "PSP v2", Intent: "move to PSP v2", BaselineID: f.base.ID})
	if err != nil {
		t.Fatal(err)
	}
	run := journal.Record{ID: "e1", ChangeID: c.ID, ProcessID: "p1", Kind: journal.KindAction, Methodology: "sdlc",
		MethodologyVersion: "1.0.0", Agent: "analyst", Action: "update_requirement", StartedAt: g.now(),
		ModelCalls: []journal.ModelCall{{Provider: "anthropic", Model: "m"}}, ToolCalls: []journal.ToolUse{{Name: "goap-graph/search"}}}
	if err := journal.Append(ctx, g, []journal.Record{run}); err != nil {
		t.Fatal(err)
	}
	items, err := g.AddItems(ctx, c.ID, []domain.ChangeItem{{Kind: domain.KindArtifact, Type: "analysis", Status: domain.ItemProposed,
		ProducedBy: "analyst", Execution: "e1", Data: map[string]any{"summary": "PSP v1 is retired"}}})
	if err != nil {
		t.Fatal(err)
	}
	pre := f.req.Ref()
	added, err := g.AddNodes(ctx, c.ID, []domain.ChangeImpact{{Intent: domain.IntentModified, Pre: &pre, Rationale: "PSP v2",
		Execution: "e1", DerivedFrom: []domain.ItemID{items[0].ID}}})
	if err != nil {
		t.Fatal(err)
	}
	written, err := g.edit(ctx, c.ID, added[0].ID, edit{Properties: map[string]any{"title": "Use PSP v2"}, Execution: "e1"})
	if err != nil {
		t.Fatal(err)
	}
	if _, err := g.accept(ctx, c.ID, added[0].ID, "alice", "ok"); err != nil {
		t.Fatal(err)
	}
	if _, err := g.Apply(ctx, c.ID, ""); err != nil {
		t.Fatal(err)
	}
	if c, err = g.Change(ctx, c.ID); err != nil {
		t.Fatal(err)
	}
	entries, _, err := g.ChangeLog(ctx, domain.LogFilter{Change: c.ID})
	if err != nil {
		t.Fatal(err)
	}
	doc, err := prov.Export(c, entries)
	if err != nil {
		t.Fatal(err)
	}
	// round trip through JSON, as a consumer reads it
	raw, err := json.Marshal(doc)
	if err != nil {
		t.Fatal(err)
	}
	var back struct {
		Graph []map[string]any `json:"@graph"`
	}
	if err := json.Unmarshal(raw, &back); err != nil {
		t.Fatal(err)
	}
	byID := map[string]map[string]any{}
	for _, n := range back.Graph {
		byID[n["@id"].(string)] = n
	}
	node := func(id string) map[string]any {
		t.Helper()
		n, ok := byID[id]
		if !ok {
			t.Fatalf("no %s in the export", id)
		}
		return n
	}
	has := func(n map[string]any, prop, want string) {
		t.Helper()
		for _, v := range values(n[prop]) {
			if s, ok := v.(string); ok && s == want {
				return
			}
			if m, ok := v.(map[string]any); ok && (m["@id"] == want || m["@value"] == want) {
				return
			}
		}
		t.Fatalf("%s %s: %v, want %s", n["@id"], prop, n[prop], want)
	}

	change := node("urn:goap:change:" + string(c.ID))
	has(change, "@type", "prov:Activity")
	has(change, "goap:intent", "move to PSP v2")
	has(change, "prov:used", "urn:goap:baseline:"+string(c.BaselineID))
	has(change, "prov:wasAssociatedWith", "urn:goap:unit:"+c.OwnerOrg)

	e1 := node("urn:goap:execution:e1")
	has(e1, "@type", "prov:Activity")
	has(e1, "goap:partOf", "urn:goap:change:"+string(c.ID))
	has(e1, "prov:wasAssociatedWith", "urn:goap:agent:sdlc%2Fanalyst")
	has(e1, "prov:wasAssociatedWith", "urn:goap:model:anthropic%2Fm")
	has(e1, "prov:wasAssociatedWith", "urn:goap:tool:goap-graph%2Fsearch")
	has(e1, "prov:used", "urn:goap:node:"+string(pre.ID)+"@v1")
	assoc := values(e1["prov:qualifiedAssociation"])[0].(map[string]any)
	if assoc["prov:hadPlan"].(map[string]any)["@id"] != "urn:goap:plan:sdlc@1.0.0%23update_requirement" {
		t.Fatalf("plan: %v", assoc)
	}

	item := node("urn:goap:item:" + string(items[0].ID))
	has(item, "prov:wasGeneratedBy", "urn:goap:execution:e1")
	has(item, "prov:wasAttributedTo", "urn:goap:principal:analyst")
	if item["data"].(map[string]any)["summary"] != "PSP v1 is retired" {
		t.Fatalf("item data: %v", item["data"])
	}

	impact := node("urn:goap:impact:" + string(added[0].ID))
	has(impact, "prov:wasDerivedFrom", "urn:goap:item:"+string(items[0].ID))
	post := "urn:goap:node:" + string(written.Post.ID) + "@v" + jsonInt(written.Post.Version)
	has(impact, "goap:post", post)
	v := node(post)
	has(v, "prov:wasGeneratedBy", "urn:goap:execution:e1")
	has(v, "prov:wasRevisionOf", "urn:goap:node:"+string(pre.ID)+"@v1")
	has(v, "prov:specializationOf", "urn:goap:node:"+string(pre.ID))

	var reviewed bool
	for _, n := range back.Graph {
		if typesOf(n)["goap:Review"] {
			reviewed = true
			has(n, "prov:wasAssociatedWith", "urn:goap:principal:alice")
			has(n, "prov:used", post)
		}
	}
	if !reviewed {
		t.Fatal("no review activity")
	}
	result := node("urn:goap:baseline:" + string(c.ResultBaselineID))
	has(result, "prov:wasGeneratedBy", "urn:goap:change:"+string(c.ID))
	has(result, "prov:hadMember", post)

	// every entry of the log is in the export, with its position
	seqs := map[float64]bool{}
	for _, n := range back.Graph {
		for _, s := range values(n["goap:seq"]) {
			seqs[s.(float64)] = true
		}
	}
	for _, e := range entries {
		if !seqs[float64(e.Seq)] {
			t.Fatalf("entry %d (%s) is not in the export", e.Seq, e.Type)
		}
	}
}

func values(v any) []any {
	if l, ok := v.([]any); ok {
		return l
	}
	if v == nil {
		return nil
	}
	return []any{v}
}

func typesOf(n map[string]any) map[string]bool {
	out := map[string]bool{}
	for _, t := range values(n["@type"]) {
		out[t.(string)] = true
	}
	return out
}

func jsonInt(v domain.Version) string {
	b, _ := json.Marshal(v)
	return string(b)
}
