// Package prov exports the log of a change (ADR 0030) as W3C PROV-O provenance, serialized as JSON-LD (ADR 0057).
//
// The change is a prov:Activity, held by its unit (a prov:Organization); every journal record of its execution is
// an activity of the change, associated with the agent that ran it under the plan of its methodology action; facts
// and node versions are entities generated by the run that produced them, attributed to their principal, derived
// from what they came from; reviews are activities using the version they judge; a landed version is a member of
// the baseline it landed in. Every journal record, fact and change impact carries its log position (goap:seq) and
// its whole record (goap:record), so the export loses nothing PROV does not model.
package prov

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strings"
	"time"

	"github.com/zimwip/goap/pkg/domain"
	"github.com/zimwip/goap/pkg/journal"
	"github.com/zimwip/goap/pkg/risk"
	"github.com/zimwip/goap/pkg/verify"
)

// Vocab is the namespace of the GOAP terms of the export; instances are named under urn:goap:.
const Vocab = "https://github.com/zimwip/goap/ns/prov#"

// MediaType is the media type of the export.
const MediaType = "application/ld+json"

// context is the JSON-LD context of the export.
var context = map[string]any{
	"prov":   "http://www.w3.org/ns/prov#",
	"xsd":    "http://www.w3.org/2001/XMLSchema#",
	"rdfs":   "http://www.w3.org/2000/01/rdf-schema#",
	"goap":   Vocab,
	"label":  "rdfs:label",
	"record": map[string]any{"@id": "goap:record", "@type": "@json"},
	"data":   map[string]any{"@id": "goap:data", "@type": "@json"},
}

// Document is a JSON-LD document.
type Document struct {
	Context map[string]any   `json:"@context"`
	Graph   []map[string]any `json:"@graph"`
}

// Export is the provenance of a change from its log entries (in the order of the log).
func Export(c domain.Change, entries []domain.LogEntry) (Document, error) {
	b := &builder{nodes: map[string]map[string]any{}, impacts: map[domain.ChangeImpactID]*domain.ChangeImpact{}}
	b.change(c)
	for _, e := range entries {
		var err error
		switch e.Stream() {
		case journal.StreamJournal:
			var r journal.Record
			if err = json.Unmarshal(e.Payload, &r); err == nil {
				b.execution(c, e, r)
			}
		case domain.LogFact:
			var it domain.ChangeItem
			if err = json.Unmarshal(e.Payload, &it); err == nil {
				b.fact(c, e, it)
			}
		case journal.StreamModel:
			var ex journal.ModelExchange
			if err = json.Unmarshal(e.Payload, &ex); err == nil {
				b.exchange(c, e, ex)
			}
		case domain.LogImpact:
			var ev domain.ImpactEvent
			if err = json.Unmarshal(e.Payload, &ev); err == nil {
				b.impact(c, e, ev)
			}
		}
		if err != nil {
			return Document{}, fmt.Errorf("log entry %d (%s): %w", e.Seq, e.Type, err)
		}
	}
	return Document{Context: context, Graph: b.graph()}, nil
}

// Names of the instances.
func iri(kind string, id string) string { return "urn:goap:" + kind + ":" + url.PathEscape(id) }

func changeIRI(id domain.ChangeID) string { return iri("change", string(id)) }
func runIRI(id string) string             { return iri("execution", id) }
func itemIRI(id domain.ItemID) string     { return iri("item", string(id)) }
func impactIRI(id domain.ChangeImpactID) string {
	return iri("impact", string(id))
}
func baselineIRI(id domain.BaselineID) string { return iri("baseline", string(id)) }
func nodeIRI(id domain.NodeID) string         { return iri("node", string(id)) }
func versionIRI(r domain.NodeRef) string {
	return iri("node", string(r.ID)) + "@v" + fmt.Sprint(r.Version)
}
func principalIRI(p string) string { return iri("principal", p) }

type builder struct {
	order []string
	nodes map[string]map[string]any
	// impacts are the change impacts as declared so far, to name what a written version revises.
	impacts map[domain.ChangeImpactID]*domain.ChangeImpact
}

func (b *builder) graph() []map[string]any {
	out := make([]map[string]any, 0, len(b.order))
	for _, id := range b.order {
		out = append(out, b.nodes[id])
	}
	return out
}

// node is the description of id, created with its types on first mention; types add up.
func (b *builder) node(id string, types ...string) map[string]any {
	n, ok := b.nodes[id]
	if !ok {
		n = map[string]any{"@id": id}
		b.nodes[id] = n
		b.order = append(b.order, id)
	}
	for _, t := range types {
		add(n, "@type", t)
	}
	return n
}

// add adds a value to a property, keeping it single while it has one value and skipping duplicates.
func add(n map[string]any, prop string, v any) {
	switch cur := n[prop].(type) {
	case nil:
		n[prop] = v
	case []any:
		for _, x := range cur {
			if same(x, v) {
				return
			}
		}
		n[prop] = append(cur, v)
	default:
		if !same(cur, v) {
			n[prop] = []any{cur, v}
		}
	}
}

func same(a, b any) bool {
	ja, _ := json.Marshal(a)
	jb, _ := json.Marshal(b)
	return string(ja) == string(jb)
}

func set(n map[string]any, prop string, v string) {
	if v != "" {
		n[prop] = v
	}
}

func ref(id string) map[string]any { return map[string]any{"@id": id} }

func at(t time.Time) any {
	return map[string]any{"@value": t.UTC().Format(time.RFC3339Nano), "@type": "xsd:dateTime"}
}

func setTime(n map[string]any, prop string, t time.Time) {
	if !t.IsZero() {
		n[prop] = at(t)
	}
}

// entry stamps a description with its log position and whole record.
func entry(n map[string]any, e domain.LogEntry) {
	add(n, "goap:seq", e.Seq)
	add(n, "goap:logType", e.Type)
	if e.Flow != "" {
		set(n, "goap:flow", e.Flow)
	}
	if len(e.Payload) > 0 {
		add(n, "record", json.RawMessage(e.Payload))
	}
}

// principal is the agent a principal or component of the log names (empty: none).
func (b *builder) principal(p string, types ...string) string {
	if p == "" {
		return ""
	}
	id := principalIRI(p)
	n := b.node(id, append([]string{"prov:Agent"}, types...)...)
	set(n, "label", p)
	return id
}

// by is the activity behind an entry: its action run, else the change itself.
func by(c domain.Change, execution string) string {
	if execution != "" {
		return runIRI(execution)
	}
	return changeIRI(c.ID)
}

func (b *builder) change(c domain.Change) {
	n := b.node(changeIRI(c.ID), "prov:Activity", "goap:Change")
	set(n, "label", c.Title)
	set(n, "goap:intent", c.Intent)
	set(n, "goap:methodology", c.Methodology)
	set(n, "goap:namespace", c.Namespace)
	set(n, "goap:status", string(c.Status))
	set(n, "goap:project", c.ProjectID)
	set(n, "goap:goal", c.Goal)
	if len(c.Data) > 0 {
		n["goap:data"] = c.Data
	}
	set(n, "goap:branch", c.Branch)
	setTime(n, "prov:startedAtTime", c.CreatedAt)
	if c.ParentID != "" {
		add(n, "goap:partOf", ref(changeIRI(c.ParentID)))
	}
	if c.OwnerOrg != "" {
		unit := iri("unit", c.OwnerOrg)
		u := b.node(unit, "prov:Agent", "prov:Organization")
		set(u, "label", c.OwnerOrg)
		add(n, "prov:wasAssociatedWith", ref(unit))
	}
	// the state the change started from (the empty state of a namespace's first change has no baseline, ADR 0056)
	if c.BaselineID != "" {
		b.node(baselineIRI(c.BaselineID), "prov:Entity", "prov:Collection", "goap:Baseline")
		add(n, "prov:used", ref(baselineIRI(c.BaselineID)))
	}
	if c.ResultBaselineID != "" {
		bl := b.node(baselineIRI(c.ResultBaselineID), "prov:Entity", "prov:Collection", "goap:Baseline")
		add(bl, "prov:wasGeneratedBy", ref(changeIRI(c.ID)))
		if c.BaselineID != "" {
			add(bl, "prov:wasRevisionOf", ref(baselineIRI(c.BaselineID)))
		}
	}
}

// execution is a journal record: an action run (or a scheduling or planning record) of the change.
func (b *builder) execution(c domain.Change, e domain.LogEntry, r journal.Record) {
	n := b.node(runIRI(r.ID), "prov:Activity", "goap:Execution")
	entry(n, e)
	label := r.Kind
	if r.Action != "" {
		label += " " + r.Action
	}
	set(n, "label", label)
	set(n, "goap:kind", r.Kind)
	set(n, "goap:process", r.ProcessID)
	set(n, "goap:action", r.Action)
	set(n, "goap:actionKind", r.ActionKind)
	set(n, "goap:status", r.Status)
	set(n, "goap:activity", r.ActivityRef)
	set(n, "goap:traceId", r.TraceID)
	if r.Error != "" {
		set(n, "goap:error", r.Error)
	}
	add(n, "goap:partOf", ref(changeIRI(c.ID)))
	setTime(n, "prov:startedAtTime", r.StartedAt)
	setTime(n, "prov:endedAtTime", r.EndedAt)

	// who ran it: the person deciding a human action, else the methodology agent, under the plan of the action
	var who string
	if r.Actor != "" {
		who = b.principal(r.Actor, "prov:Person")
	} else if r.Agent != "" {
		who = iri("agent", r.Methodology+"/"+r.Agent)
		a := b.node(who, "prov:Agent", "prov:SoftwareAgent", "goap:MethodologyAgent")
		set(a, "label", r.Agent)
		set(a, "goap:planner", r.Planner)
	}
	if who != "" {
		add(n, "prov:wasAssociatedWith", ref(who))
		assoc := map[string]any{"@type": "prov:Association", "prov:agent": ref(who)}
		if r.Action != "" {
			version := r.Methodology
			if r.MethodologyVersion != "" {
				version += "@" + r.MethodologyVersion
			}
			plan := iri("plan", version+"#"+r.Action)
			p := b.node(plan, "prov:Entity", "prov:Plan", "goap:Action")
			set(p, "label", r.Action)
			set(p, "goap:methodology", r.Methodology)
			set(p, "goap:methodologyVersion", r.MethodologyVersion)
			assoc["prov:hadPlan"] = ref(plan)
		}
		add(n, "prov:qualifiedAssociation", assoc)
	}
	// the models and tools it called act on its behalf
	for _, m := range r.ModelCalls {
		name := strings.Trim(m.Provider+"/"+m.Model, "/")
		if name == "" {
			continue
		}
		id := iri("model", name)
		mn := b.node(id, "prov:Agent", "prov:SoftwareAgent", "goap:Model")
		set(mn, "label", name)
		add(n, "prov:wasAssociatedWith", ref(id))
	}
	for _, t := range r.ToolCalls {
		id := iri("tool", t.Name)
		tn := b.node(id, "prov:Agent", "prov:SoftwareAgent", "goap:Tool")
		set(tn, "label", t.Name)
		add(n, "prov:wasAssociatedWith", ref(id))
	}
	// the node versions it started from
	for _, rd := range r.Reads {
		add(n, "prov:used", ref(b.version(rd, "", "")))
	}
	if r.ParentProcessID != "" {
		set(n, "goap:parentProcess", r.ParentProcessID)
	}
}

// exchange is the request and the answer of an LLM call: an entity the action run generated, with the texts.
func (b *builder) exchange(c domain.Change, e domain.LogEntry, ex journal.ModelExchange) {
	n := b.node(iri("exchange", e.ID), "prov:Entity", "goap:ModelExchange")
	entry(n, e)
	set(n, "label", "model call "+e.Subject)
	set(n, "goap:system", ex.System)
	set(n, "goap:response", ex.Response)
	if ex.Truncated {
		n["goap:truncated"] = true
	}
	setTime(n, "prov:generatedAtTime", e.At)
	add(n, "prov:wasGeneratedBy", ref(by(c, e.Execution)))
	if p := b.principal(e.By); p != "" {
		add(n, "prov:wasAttributedTo", ref(p))
	}
}

// fact is an item of the change's blackboard.
func (b *builder) fact(c domain.Change, e domain.LogEntry, it domain.ChangeItem) {
	n := b.node(itemIRI(it.ID), "prov:Entity", "goap:Item")
	entry(n, e)
	set(n, "goap:kind", string(it.Kind))
	set(n, "goap:type", it.Type)
	set(n, "goap:status", string(it.Status))
	label := string(it.Kind)
	if it.Type != "" {
		label += " " + it.Type
	}
	set(n, "label", label)
	setTime(n, "prov:generatedAtTime", it.CreatedAt)
	add(n, "prov:wasGeneratedBy", ref(by(c, it.Execution)))
	if p := b.principal(e.By); p != "" {
		add(n, "prov:wasAttributedTo", ref(p))
	}
	for _, d := range it.DerivedFrom {
		add(n, "prov:wasDerivedFrom", ref(itemIRI(d)))
	}
	for _, s := range it.Supersedes {
		add(n, "prov:wasRevisionOf", ref(itemIRI(s)))
	}
	if d := it.Decision; d != nil {
		add(n, "goap:decides", ref(itemIRI(d.Item)))
		n["goap:accept"] = d.Accept
		set(n, "rdfs:comment", d.Comment)
	}
	if it.Kind == domain.KindTransition {
		// a move of the lifecycle of the change (ADR 0058), influenced by the decision point that gated it
		if d, _ := it.Data["decision"].(string); d != "" {
			add(n, "prov:wasInfluencedBy", ref(itemIRI(domain.ItemID(d))))
		}
	}
	if it.Kind == verify.KindVerification {
		b.verification(n, it)
	}
	if it.Kind == risk.KindDerogation {
		b.derogation(n, it)
	}
	if len(it.Data) > 0 {
		n["data"] = it.Data
	}
}

// verification maps a state of the verification of an effect (ADR 0075): the entity is a Verification of the change
// impacts it covers, attributed to the verifier once the effect is judged.
func (b *builder) verification(n map[string]any, it domain.ChangeItem) {
	add(n, "@type", "goap:Verification")
	str := func(k string) string { s, _ := it.Data[k].(string); return s }
	set(n, "goap:state", str(verify.KeyState))
	set(n, "goap:oracle", str(verify.KeyOracle))
	set(n, "label", "verification "+str(verify.KeyState))
	for _, id := range append(verify.Impacts(it), str(verify.KeyImpact)) {
		if id != "" {
			add(n, "prov:wasDerivedFrom", ref(impactIRI(domain.ChangeImpactID(id))))
		}
	}
	if by := str(verify.KeyBy); by != "" {
		if p := b.principal(by); p != "" {
			add(n, "prov:wasAttributedTo", ref(p))
		}
	}
}

// derogation maps a version of a derogation (ADR 0075 §2): an entity of the rule it waives, of its target and expiry,
// attributed to the signatory who answers for it.
func (b *builder) derogation(n map[string]any, it domain.ChangeItem) {
	add(n, "@type", "goap:Derogation")
	str := func(k string) string { s, _ := it.Data[k].(string); return s }
	set(n, "goap:rule", str("rule"))
	set(n, "goap:target", str("target"))
	set(n, "goap:expires", str("expires"))
	set(n, "goap:derogationStatus", str("status"))
	set(n, "label", "derogation "+str("key"))
	if p := b.principal(str("signatory")); p != "" {
		add(n, "prov:wasAttributedTo", ref(p))
	}
}

// version is the entity of a node version; typ and key describe the node when known.
func (b *builder) version(r domain.NodeRef, typ, key string) string {
	id := versionIRI(r)
	n := b.node(id, "prov:Entity", "goap:NodeVersion")
	set(n, "label", r.String())
	add(n, "prov:specializationOf", ref(nodeIRI(r.ID)))
	node := b.node(nodeIRI(r.ID), "prov:Entity", "goap:Node")
	set(node, "label", string(r.ID))
	set(node, "goap:type", typ)
	set(node, "goap:key", key)
	return id
}

// impact is an event of a change impact (ADR 0029).
func (b *builder) impact(c domain.Change, e domain.LogEntry, ev domain.ImpactEvent) {
	actor := b.principal(ev.By)
	if ev.Op == domain.ImpactAdopted {
		// change level: a flow branch is adopted, replacing the runs it makes stale (ADR 0025)
		a := b.node(iri("adoption", ev.ID), "prov:Activity", "goap:Adoption")
		entry(a, e)
		set(a, "label", "adopt "+ev.Flow)
		setTime(a, "prov:startedAtTime", ev.At)
		setTime(a, "prov:endedAtTime", ev.At)
		add(a, "goap:partOf", ref(changeIRI(c.ID)))
		if actor != "" {
			add(a, "prov:wasAssociatedWith", ref(actor))
		}
		for _, s := range ev.Stale {
			add(a, "goap:replaces", ref(runIRI(s)))
		}
		return
	}
	imp := impactIRI(ev.Impact)
	n := b.node(imp, "prov:Entity", "goap:ChangeImpact")
	entry(n, e)
	add(n, "goap:change", ref(changeIRI(c.ID)))
	state := b.impacts[ev.Impact]
	typ, key := "", ""
	if state != nil {
		typ, key = state.Type, state.Key
	}
	// a proposal adds the change impact (State); so does a creation, whose one event is also its first version
	// (Post, below): ADR 0077
	propose := func() {
		if s := ev.State; s != nil {
			cp := *s
			b.impacts[ev.Impact] = &cp
			set(n, "label", s.Key)
			set(n, "goap:key", s.Key)
			set(n, "goap:type", s.Type)
			set(n, "goap:intent", string(s.Intent))
			set(n, "goap:rationale", s.Rationale)
			for _, d := range s.DerivedFrom {
				add(n, "prov:wasDerivedFrom", ref(itemIRI(d)))
			}
			for _, it := range s.Items {
				add(n, "prov:wasDerivedFrom", ref(itemIRI(it)))
			}
			if s.Pre != nil {
				add(n, "goap:pre", ref(b.version(*s.Pre, s.Type, s.Key)))
				add(b.node(by(c, ev.Execution)), "prov:used", ref(versionIRI(*s.Pre)))
			}
		}
		setTime(n, "prov:generatedAtTime", ev.At)
		add(n, "prov:wasGeneratedBy", ref(by(c, ev.Execution)))
		if actor != "" {
			add(n, "prov:wasAttributedTo", ref(actor))
		}
	}
	switch ev.Op {
	case domain.ImpactProposed:
		propose()
	case domain.ImpactTransitioned, domain.ImpactCheckedOut, domain.ImpactCreated:
		if !ev.WritesVersion() {
			return // a transition taken in place on the working version writes none (ADR 0077): only its entry
		}
		if ev.Op == domain.ImpactCreated {
			propose()
			state = b.impacts[ev.Impact]
			if state != nil {
				typ, key = state.Type, state.Key
			}
		}
		if ev.Post == nil {
			return
		}
		v := b.node(b.version(*ev.Post, typ, key))
		setTime(v, "prov:generatedAtTime", ev.At)
		add(v, "prov:wasGeneratedBy", ref(by(c, ev.Execution)))
		if actor != "" {
			add(v, "prov:wasAttributedTo", ref(actor))
		}
		if state != nil && state.Pre != nil {
			add(v, "prov:wasRevisionOf", ref(b.version(*state.Pre, typ, key)))
		}
		// a merge or a split derives its new node from the nodes it replaces (ADR 0077)
		for _, o := range originsOf(ev.Patch) {
			add(v, "prov:wasDerivedFrom", ref(b.version(o.ref, typ, o.key)))
		}
		add(n, "goap:post", ref(versionIRI(*ev.Post)))
		if state != nil {
			p := *ev.Post
			state.Post = &p
		}
	case domain.ImpactReviewed, domain.ImpactDiscarded:
		// a review is an activity of its reviewer, judging the version written
		rv := b.node(iri("review", ev.ID), "prov:Activity", "goap:Review")
		entry(rv, e)
		set(rv, "goap:op", string(ev.Op))
		setTime(rv, "prov:startedAtTime", ev.At)
		setTime(rv, "prov:endedAtTime", ev.At)
		add(rv, "goap:partOf", ref(changeIRI(c.ID)))
		add(rv, "goap:about", ref(imp))
		if actor != "" {
			add(rv, "prov:wasAssociatedWith", ref(actor))
		}
		if r := ev.Review; r != nil {
			set(rv, "label", string(ev.Op)+" "+string(r.Status))
			set(rv, "goap:status", string(r.Status))
			set(rv, "rdfs:comment", r.Comment)
		}
		if state != nil && state.Post != nil {
			add(rv, "prov:used", ref(versionIRI(*state.Post)))
		}
	case domain.ImpactLanded:
		if ev.Landed == nil {
			return
		}
		v := b.node(b.version(*ev.Landed, typ, key))
		add(n, "goap:landed", ref(versionIRI(*ev.Landed)))
		if state != nil && state.Post != nil && *state.Post != *ev.Landed {
			// a merge version of a node changed on both sides (ADR 0032)
			add(v, "prov:wasDerivedFrom", ref(versionIRI(*state.Post)))
			add(v, "prov:wasGeneratedBy", ref(by(c, ev.Execution)))
			setTime(v, "prov:generatedAtTime", ev.At)
		}
		if ev.Baseline != "" {
			// a state the change left: on its own branch when committed, on the target when integrated (ADR 0056)
			bl := b.node(baselineIRI(ev.Baseline), "prov:Entity", "prov:Collection", "goap:Baseline")
			add(bl, "prov:wasGeneratedBy", ref(changeIRI(c.ID)))
			add(bl, "prov:hadMember", ref(versionIRI(*ev.Landed)))
		}
	case domain.ImpactRebased:
		if ev.Pre != nil {
			add(n, "goap:rebasedOn", ref(b.version(*ev.Pre, typ, key)))
			if state != nil {
				p := *ev.Pre
				state.Pre = &p
			}
		}
	}
}

type origin struct {
	ref domain.NodeRef
	key string
}

// originsOf reads the origins of a created event (ADR 0077): the patch is what the log stored, so its numbers and
// lists come back from JSON.
func originsOf(patch map[string]any) []origin {
	var out []origin
	list, _ := patch["origins"].([]any)
	for _, x := range list {
		m, ok := x.(map[string]any)
		if !ok {
			continue
		}
		id, _ := m["id"].(string)
		var v int
		switch n := m["version"].(type) {
		case float64:
			v = int(n)
		case int:
			v = n
		}
		key, _ := m["key"].(string)
		if id != "" && v > 0 {
			out = append(out, origin{domain.NodeRef{ID: domain.NodeID(id), Version: domain.Version(v)}, key})
		}
	}
	return out
}
