<script lang="ts">
  // The flow of a process, or of a method composing its own steps, from the draft as edited, with its consistency drawn
  // in it: what a level cannot reach is shown as unresolved inputs and unreached outputs (CheckLevels).
  import ProcessFlowView from './ProcessFlowView.svelte';
  import { registry, errorMessage, type Issue, type LevelCheck, type PlanPreview, type ProcessGraph } from '../api';
  import { splitIssues } from '../issues';
  import { fromForm } from '../methodologyForm';
  import type { Draft } from '../stores/drafts.svelte';

  let {
    draft: d,
    root,
    plan,
    focus = '',
    at = '',
    only = '',
    onstep,
    onmethod,
  }: {
    draft: Draft;
    root: string;
    plan?: PlanPreview;
    focus?: string;
    at?: string;
    only?: string;
    onstep?: (path: string) => void;
    onmethod?: (name: string) => void;
  } = $props();

  let graph = $state<ProcessGraph | undefined>();
  let levels = $state<LevelCheck[]>([]);
  let issue = $state('');
  // the rules the draft breaks: the graph is drawn as far as it stands, each issue tied to the step it is about
  let ruled = $state<Issue[]>([]);
  // the dynamic conditions the methodology knows (declared, platform, generated by the steps), evaluated over the state
  // of the change: what no step makes true is read from there
  let known = $state<{ name: string; expr: string }[] | undefined>();
  const conditions = $derived(known);
  const snapshot = $derived(JSON.stringify(d.form));

  $effect(() => {
    void snapshot;
    const name = root.trim();
    if (!name) return;
    const ctl = new AbortController();
    const timer = setTimeout(() => {
      const m = fromForm(d.form).methodology;
      Promise.all([registry.processGraph(m, name, ctl.signal), registry.checkLevels(m, name, ctl.signal)])
        .then(([g, l]) => {
          graph = g.graph ?? graph;
          levels = l.levels ?? levels;
          if (l.conditions) known = Object.entries(l.conditions).map(([name, expr]) => ({ name, expr }));
          ruled = splitIssues(g.issues?.length ? g.issues : (l.issues ?? [])).errors; // the remarks are not drawn on the flow
          issue = !g.graph && ruled.length ? `The draft does not compile (${ruled.length} issue(s), see the Issues console) and nothing of this flow can be drawn.` : '';
        })
        .catch((e) => {
          if (!ctl.signal.aborted) issue = errorMessage(e);
        });
    }, 400);
    return () => (clearTimeout(timer), ctl.abort());
  });
</script>

{#if issue}
  <p class="hint">{issue}</p>
  {#if !graph}
    <ul class="hint">{#each ruled as i, k (k)}<li><code>{i.path}</code> {i.message}</li>{/each}</ul>
  {/if}
{/if}
{#if graph}
  <ProcessFlowView {graph} issues={ruled} {plan} {levels} {focus} {at} {only} {conditions} {onstep} {onmethod} />
{:else if !issue}
  <p class="empty">Building the graph…</p>
{/if}
