<script lang="ts">
  // The flow of a process, or of a method composing its own steps, from the draft as edited, with its consistency drawn
  // in it: what a level cannot reach is shown as unresolved inputs and unreached outputs (CheckLevels).
  import ProcessFlowView from './ProcessFlowView.svelte';
  import { registry, errorMessage, type LevelCheck, type PlanPreview, type ProcessGraph } from '../api';
  import { fromForm } from '../methodologyForm';
  import type { Draft } from '../stores/drafts.svelte';

  let {
    draft: d,
    root,
    plan,
    focus = '',
    at = '',
    only = '',
    onstep,
    onmethod,
  }: {
    draft: Draft;
    root: string;
    plan?: PlanPreview;
    focus?: string;
    at?: string;
    only?: string;
    onstep?: (path: string) => void;
    onmethod?: (name: string) => void;
  } = $props();

  let graph = $state<ProcessGraph | undefined>();
  let levels = $state<LevelCheck[]>([]);
  let issue = $state('');
  // the dynamic conditions the methodology knows (declared, platform, generated by the steps), evaluated over the state
  // of the change: what no step makes true is read from there
  let known = $state<{ name: string; expr: string }[] | undefined>();
  const conditions = $derived(known);
  const snapshot = $derived(JSON.stringify(d.form));

  $effect(() => {
    void snapshot;
    const name = root.trim();
    if (!name) return;
    const ctl = new AbortController();
    const timer = setTimeout(() => {
      const m = fromForm(d.form).methodology;
      Promise.all([registry.processGraph(m, name, ctl.signal), registry.checkLevels(m, name, ctl.signal)])
        .then(([g, l]) => {
          graph = g.graph ?? graph;
          levels = l.levels ?? levels;
          if (l.conditions) known = Object.entries(l.conditions).map(([name, expr]) => ({ name, expr }));
          issue = g.issues?.length ? `The draft does not compile (${g.issues.length} issue(s), see the Issues console): the graph shows its last valid state.` : '';
        })
        .catch((e) => {
          if (!ctl.signal.aborted) issue = errorMessage(e);
        });
    }, 400);
    return () => (clearTimeout(timer), ctl.abort());
  });
</script>

{#if issue}<p class="hint">{issue}</p>{/if}
{#if graph}
  <ProcessFlowView {graph} {plan} {levels} {focus} {at} {only} {conditions} {onstep} {onmethod} />
{:else if !issue}
  <p class="empty">Building the graph…</p>
{/if}
